// angular/src/components/create-message/create-message.component.ts
import { Component, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'create-message',
  templateUrl: './create-message.component.html',
  styleUrls: ['./create-message.component.css']
})
export class CreateMessageComponent {
  message: string = '';

  @Output() createMessageEvent = new EventEmitter<string>();

  onSubmit(): void {
    if (!this.message.trim()) {
      return;
    }

    this.createMessageEvent.emit(this.message);
    this.message = '';
  }
}

<form class="form" (ngSubmit)="onSubmit()">
  <label for="message">New Message</label>
  <textarea
    class="textarea"
    id="message"
    name="message"
    [(ngModel)]="message"
  ></textarea>
  <div>
    <input class="submit" type="submit" value="Post"/>
  </div>
</form>

// react/src/create-message/create-message.js
import React from 'react';
import styles from './create-message.modules.css';

export default class CreateMessage extends React.Component {
  constructor(props) {
    super(props);
    this.state = { message: '' };
  }

  onSubmit(event) {
    event.preventDefault();

    if (!this.state.message.trim()) {
      return;
    }

    this.props.onCreate(this.state.message);
    this.setState({ message: '' });
  }

  onChange(event) {
    this.setState({ message: event.target.value })
  }

  render () {
    return <form className={styles.form} onSubmit={(e) => this.onSubmit(e)}>
      <label htmlFor="message">New Message</label>
      <textarea
        className={styles.textarea}
        id="message"
        value={this.state.message}
        onChange={(e) => this.onChange(e)}
      ></textarea>
      <div>
        <input className={styles.submit} type="submit" value="Post"/>
      </div>
    </form>
  }
}
