// angular/src/components/social-button/social-button.component.ts
import { Component, Input } from '@angular/core';
import { formatStat } from '../../utils';

@Component({
  selector: 'social-button',
  templateUrl: './social-button.component.html',
  styleUrls: ['./social-button.component.css']
})
export class SocialButtonComponent {
  @Input() title: string = '';
  @Input() icon: string = '';

  public get count(): number {
   return this._count;
  }

  @Input()
  public set count(count: number) {
    this._count = count;
    this.formattedCount = formatStat(count);
  }

  public get pressed(): boolean {
   return this._pressed;
  }

  @Input()
  public set pressed(pressed: boolean) {
    this._pressed = pressed;
    this.className = `social-button ${pressed ? 'pressed' : ''}`;
    this.iconName = `${this.icon}${pressed ? '_filled' : ''}`;
  }

  className: string = '';
  formattedCount: number = 0;
  iconName: string = '';

  private _count: number = 0;
  private _pressed: boolean = false;

  onClick(): void {
    this.pressed = !this.pressed;
    this.count = this.count + (this.pressed ? 1 : -1);
  }
}

<div
  [class]="className"
  [title]="title"
  (click)="onClick()"
>
  <icon [name]="iconName" [alt]="title"></icon>
  {{ formattedCount }}
</div>

// react/src/social-button/social-button.jsx
import React from 'react';
import Icon from '../icon/icon';
import styles from './social-button.modules.css';
import { formatStat } from '../utils';

export default class SocialButton extends React.Component {
  constructor(props) {
    super(props);
    const { count, pressed } = props;
    this.state = { count, pressed };
  }

  onClick() {
    const pressed = !this.state.pressed;
    const count = this.state.count + (pressed ? 1 : -1);
    this.setState({ count, pressed });
    this.props.onClick?.();
  }

  render() {
    const { title, icon } = this.props;
    const { count, pressed } = this.state;

    const iconName = `${icon}${pressed ? '_filled' : ''}`;
    const className = `${styles.socialButton} ${pressed ? styles.pressed : ''}`;

    return <div
      className={className}
      title={title}
      onClick={() => this.onClick()}
    >
      <Icon name={iconName} alt={title}></Icon>
      {formatStat(count)}
    </div>
  }
}
