// react/src/components/app/app.jsx
import React from 'react';
import MessageList from '../message-list/message-list';
import Icon from '../icon/icon';
import CreateMessage from '../create-message/create-message';
import styles from './app.modules.css';

// pretend we got this from a database query
import messages from '../../assets/messages';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = { messages, focus: false };
    this.createMessage = this.createMessage.bind(this);
    this.deleteMessage = this.deleteMessage.bind(this);
  }

  /**
   * Create a new message state object.
   * @param {String} message - User message.
   */
  createMessage(message) {
    const newMessage = {
      // a mock id and user data
      id: Math.random(),
      user: {
        name: 'Sam Mills',
        handle: '@sam_mills',
        link: '/users/@sam_mills',
        profile: '/src/assets/sam-profile.png'
      },
      timestamp: (new Date()).toISOString(),
      message,
      comments: [],
      likes: 0,
      sympathy: 0,
      shares: 0
    };
    this.setState({ messages: [newMessage, ...this.state.messages], focus: true });
  }

  /**
   * Delete a message from the messages state.
   * @param {Number} id - ID of the message to delete.
   */
  deleteMessage(id) {
    this.setState({ messages: this.state.messages.filter(message => message.id !== id), focus: true });
  }

  render() {
    return <div className={styles.app}>
      <header className={styles.header}>
        <img className={styles.icon} src="/src/assets/react-logo.svg" alt=""/>
        <h1 className={styles.title}>Home</h1>
      </header>
      <main className={styles.body}>
        <CreateMessage onCreate={this.createMessage}/>
        <MessageList messages={this.state.messages} onDelete={this.deleteMessage} focus={this.state.focus}/>
      </main>
    </div>
  }
}

// angular/src/components/app/app.component.ts
import { Component } from '@angular/core';

// pretend we got this from a database query
import messageData from '../../assets/messages';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  messages = messageData;
  focus: boolean = false;

  /**
   * Create a new message state object.
   * @param {String} message - User message.
   */
  createMessage(message: string): void {
    const newMessage = {
      // a mock id and user data
      id: Math.random(),
      user: {
        name: 'Sam Mills',
        handle: '@sam_mills',
        link: '/users/@sam_mills',
        profile: '/assets/sam-profile.png'
      },
      timestamp: (new Date()).toISOString(),
      message,
      comments: [],
      likes: 0,
      sympathy: 0,
      shares: 0
    };
    this.messages = [newMessage, ...this.messages];
  }

  /**
   * Delete a message from the messages state.
   * @param {Number} id - ID of the message to delete.
   */
  deleteMessage(id: number) {
    this.messages = this.messages.filter(message => message.id !== id);
    this.focus = true;
  }
}

<div class="app">
  <header class="header">
    <img class="icon" src="/assets/angular-logo.svg" alt=""/>
    <h1 class="title">Home</h1>
  </header>
  <main class="body">
    <create-message (createMessageEvent)="createMessage($event)"></create-message>
    <message-list [messages]="messages" (deleteMessageEvent)="deleteMessage($event)" [focus]="focus"></message-list>
  </main>
</div>
