// vue/src/components/message-list/message-list.vue
<template>
  <ul class="message-list">
    <li v-for="(message, index) in messages">
      <MessageItem v-bind="message" @delete="onDelete" :focus="focus && index === 0 ? true : null" />
    </li>
  </ul>
</template>

<script>
import MessageItem from '../message-item/message-item.vue';

export default {
  name: 'MessageList',
  props: ['messages', 'focus'],
  components: {
    MessageItem
  },
  methods: {
    onDelete(id) {
      this.$emit('delete', id);
    }
  }
}
</script>

<style scoped>
.message-list {
  list-style: none;
  display: flex;
  flex-direction: column;
  row-gap: 1rem;
  padding: 0;
}
</style>

// react/src/components/message-list/message-list.jsx
import React from 'react';
import MessageItem from '../message-item/message-item';
import styles from './message-list.modules.css';

export default class MessageList extends React.Component {
  render() {
    const { messages, onDelete, focus } = this.props;

    const messageList = messages.map((message, index) => {
      return <li key={message.id}><MessageItem {...message} deleteMessage={() => onDelete(message.id)} focus={index === 0 && focus}/></li>
    });

    return <ul className={styles.messageList}>{messageList}</ul>
  }
}
