// angular/src/components/message-item/message-item.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { getTime } from '../../utils';
import { User, Message } from '../../types';

@Component({
  selector: 'message-item',
  templateUrl: './message-item.component.html',
  styleUrls: ['./message-item.component.css']
})
export class MessageItemComponent {
  @Input() id: number = 0;
  @Input() user: User = {
    name: '',
    handle: '',
    link: '',
    profile: ''
  };
  @Input() message: string = '';
  @Input() comments: Message[] = [];
  @Input() likes: number = 0;
  @Input() sympathy: number = 0;
  @Input() shares: number = 0;

  public get timestamp(): string {
   return this._timestamp;
  }

  @Input()
  public set timestamp(timestamp: string) {
    this._timestamp = timestamp;
    this.relativeTime = getTime(timestamp);
  }

  @Output() deleteMessageEvent = new EventEmitter<number>();

  userCommented: boolean = false;
  userLiked: boolean = false;
  userSympathy: boolean = false;
  userShared: boolean = false;
  relativeTime: string = '';

  private _timestamp: string = '';

  deleteMessage() {
    this.deleteMessageEvent.emit(this.id);
  }
}

<div class="message-item">
  <div>
    <img class="profile" [src]="user.profile" alt="" />
  </div>
  <div class="message">
    <div class="header">
      <a class="link" [href]="user.link">
        <span class="name">{{ user.name }}</span>
        <span class="handle">{{ user.handle }}</span>
      </a>
      <div class="date">{{ relativeTime }}</div>
      <button
        class="delete"
        title="Delete"
        (click)="deleteMessage()"
      >
        <icon name="delete" alt="Delete"></icon>
      </button>
    </div>
    <div class="body">
      {{ message }}
    </div>
    <div class="footer">
      <ul class="list">
        <li>
          <social-button icon="comment" title="Comment" [count]="comments.length" [pressed]="userCommented"></social-button>
        </li>
        <li>
          <social-button icon="like" title="Like" [count]="likes" [pressed]="userLiked"></social-button>
        </li>
        <li>
          <social-button icon="sympathize" title="Sympathize" [count]="sympathy" [pressed]="userSympathy"></social-button>
        </li>
        <li>
          <social-button icon="share" title="Share" [count]="shares" [pressed]="userShared"></social-button>
        </li>
      </ul>
    </div>
  </div>
</div>

// react/src/components/message-item/message-item.jsx
import React from 'react';
import styles from './message-item.modules.css';
import Icon from '../icon/icon';
import SocialButton from '../social-button/social-button';
import { getTime } from '../../utils';

export default class MessageItem extends React.Component {
  constructor(props) {
    super(props);
    const { likes, sympathy, shares } = props;
    this.state = {
      userCommented: false,
      likes,
      userLiked: false,
      sympathy,
      userSympathy: false,
      shares,
      userShared: false
    };
  }

  render () {
    const {
      id,
      user,
      timestamp,
      message,
      comments,
      deleteMessage
    } = this.props;
    const {
      userCommented,
      likes,
      userLiked,
      sympathy,
      userSympathy,
      shares,
      userShared
    } = this.state;

    return <div className={styles.messageItem}>
      <div>
        <img className={styles.profile} src={user.profile} alt="" />
      </div>
      <div className={styles.message}>
        <div className={styles.header}>
          <a className={styles.link} href={user.link}>
            <span className={styles.name}>{user.name}</span>
            <span className={styles.handle}>{user.handle}</span>
          </a>
          <div className={styles.date}>{getTime(timestamp)}</div>
          <button
            className={styles.delete}
            title="Delete"
            onClick={() => deleteMessage(id)}
          >
            <Icon name="delete" alt="Delete"/>
          </button>
        </div>
        <div className={styles.body}>
          {message}
        </div>
        <div className={styles.footer}>
          <ul className={styles.list}>
            <li>
              <SocialButton icon="comment" title="Comment" count={comments.length} pressed={userCommented}/>
            </li>
            <li>
              <SocialButton icon="like" title="Like" count={likes} pressed={userLiked}/>
            </li>
            <li>
              <SocialButton icon="sympathize" title="Sympathize" count={sympathy} pressed={userSympathy}/>
            </li>
            <li>
              <SocialButton icon="share" title="Share" count={shares} pressed={userShared}/>
            </li>
          </ul>
        </div>
      </div>
    </div>
  }
}
